---
functional:
  - Пользователь может поменять свой никнейм 
  - Пользователь может выбрать звук для окончания раунда
  - Пользователь может регулировать громкость звука уведомлений
  - Пользователь может найти другого пользователя по никнейму
  - Пользователь может добавить в друзья другого пользователя
  - Пользователь может видеть количество пользователей онлайн
  - Пользователь может просматривать турниры
  - Пользователь может просматривать список задач других пользователей
  - Пользователь может создать свою задачу
  - Пользователь может создать свое задание
  - Пользователь может создать свой турнир
  - Пользователь может зарегистрироваться через электронную почту
  - Пользователь может авторизоваться через GitHub
  - Пользователь может авторизоваться через Discord
  - Пользователь может сбросить пароль
  - Незарегистрированный пользователь может запустить игру
  - Пользователь может создать игру
  - Пользователь может выбрать уровень сложности в игре
  - Пользователь может задать время на выполнение задания
  - Пользователь может назначить противником бота
  - Пользователь может выбрать другого игрока в качестве противника
  - Пользователь может выбрать в качестве противника друга из списка
  - Пользователь может выбрать задание из представленного списка
  - Пользователь может выбрать игру по тегам
  - Пользователь может прочитать руководство к выполнению задания
  - Пользователь может выбрать язык для прочтения задания (EN, RU)
  - Пользователь может выбрать язык программирования для решения задач
  - Пользователь может видить в онлайн режиме редактор кода соперника
  - Пользователь может удалять, вставлять, писать данные в редакторе кода
  - Пользователь может видеть информацию о сопернике
  - Пользователь может сдаться
  - Пользователь может сбросить решение в редакторе кода 
  - Пользователь может проверить решение
  - Пользователь может вернуться в игру пока не вышло время
  - Пользователь может вернуться на главную страницу после завершения игры
  - Пользователь может присоединиться к игре, созданной другим пользователем
  - Пользователь может просматривать таблицу лидеров (за все время, за месяц, за неделю)
  - Пользователь может просматривать свою статистику
  - Пользователь может просматривать завершенные игры
non-functional:
  - Сайт должен быть отказоустойчив
  - Сайт должен быть локализован (должен поддерживать несколько языов)
  - Сайт должен быть доступен большую часть времени для пользователей
  - Сайт должен быть удобным в использовании (интуитивно понятный с простой навигацией)
  - Дизайн сайта должен быть адаптивным для всех расширений экранов
  - Сайт должен защищать личные данные пользователей
  - Сайт должен быть крос-браузерным
  - Сайт должен обрабатывать одновременно 1000 пользователей без ухудшения скорости загрузки
implicit:
  - Поддержка различных языков програмирования
  - Награды за участие в турнирах
  - Привлекательный дизайн сайта
  - Возможность коммуникации между пользователями в виде чата, форума или комментариев
  - Поддержка обратной связи между пользователями и командой разработки для реагирования на возможные предложения по улучшению продукта
